import type {
  ActionOwner,
  Claim,
  ClaimActivityEvent,
  ClaimStage,
  ClaimStageKey,
  ExplainabilityNote,
  MemberProfile,
  PassbookEntry,
  Service,
  ServiceStatus,
  SupportTicket,
} from "@/types/epf";

const monthDate = (value: string) => new Date(`${value}-01T00:00:00.000Z`);

type MonthlySeriesEntry = {
  month: string;
  employee: number;
  employer: number;
  eps: number;
  interest: number;
  transferIn?: number;
  withdrawal?: number;
  adjustment?: number;
  employerName?: string;
  note?: string;
};

const MONTHLY_SERIES: MonthlySeriesEntry[] = [
  {
    month: "2024-07",
    employee: 7700,
    employer: 7700,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2024-08",
    employee: 7700,
    employer: 7700,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2024-09",
    employee: 7800,
    employer: 7800,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2024-10",
    employee: 7800,
    employer: 7800,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2024-11",
    employee: 7800,
    employer: 7800,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2024-12",
    employee: 7900,
    employer: 7900,
    eps: 1250,
    interest: 4700,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-01",
    employee: 7900,
    employer: 7900,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-02",
    employee: 7900,
    employer: 7900,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-03",
    employee: 8000,
    employer: 8000,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-04",
    employee: 8000,
    employer: 8000,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-05",
    employee: 8100,
    employer: 8100,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-06",
    employee: 8100,
    employer: 8100,
    eps: 1250,
    interest: 5300,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-07",
    employee: 8100,
    employer: 8100,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-08",
    employee: 8200,
    employer: 8200,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-09",
    employee: 8200,
    employer: 8200,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-10",
    employee: 8200,
    employer: 8200,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-11",
    employee: 8300,
    employer: 8300,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2025-12",
    employee: 8300,
    employer: 8300,
    eps: 1250,
    interest: 6100,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2026-01",
    employee: 8300,
    employer: 8300,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2026-02",
    employee: 8400,
    employer: 8400,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2026-03",
    employee: 8400,
    employer: 8400,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2026-04",
    employee: 8400,
    employer: 8400,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2026-05",
    employee: 8500,
    employer: 8500,
    eps: 1250,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
  },
  {
    month: "2026-06",
    employee: 6200,
    employer: 6200,
    eps: 980,
    interest: 0,
    employerName: "Nidhi Manufacturing Pvt Ltd",
    adjustment: -450,
    note: "Partial payroll period due to job transition in this dataset.",
  },
  {
    month: "2026-07",
    employee: 8500,
    employer: 8500,
    eps: 1250,
    interest: 0,
    transferIn: 32500,
    employerName: "Nidhi Manufacturing Pvt Ltd",
    note: "Transfer-in from previous PF account posted in this month.",
  },
];

export const mockPassbook: PassbookEntry[] = MONTHLY_SERIES.map((item, index) => ({
  id: `PB-${index + 1}`,
  postedAt: monthDate(item.month).toISOString(),
  wageMonth: item.month,
  employeeContribution: item.employee,
  employerContribution: item.employer,
  epsContribution: item.eps,
  interestCredit: item.interest,
  transferIn: item.transferIn,
  withdrawal: item.withdrawal,
  adjustment: item.adjustment,
  employerName: item.employerName,
  note: item.note,
}));

const claimStageSequence: Array<{
  key: ClaimStageKey;
  label: string;
  detail: string;
  owner: ActionOwner;
  requiresUserAction: boolean;
  userAction: string;
  expectedDuration: string;
  nextStep: string;
  explanation: ExplainabilityNote;
}> = [
  {
    key: "submitted",
    label: "Claim submitted",
    detail: "Your claim request has been captured with reference details.",
    owner: "user",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "Immediately",
    nextStep: "Automated eligibility checks",
    explanation: {
      owner: "user",
      whatHappened: "Your claim was submitted successfully.",
      whyItHappened: "The form passed basic input validation.",
      userImpact: "A tracking timeline is now available.",
      nextSteps: ["Wait for automated checks to complete."],
    },
  },
  {
    key: "initial_checks",
    label: "Automated eligibility checks",
    detail: "System checks service history, KYC linkage, and form consistency.",
    owner: "system",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "Within a few hours",
    nextStep: "Identity and KYC verification",
    explanation: {
      owner: "system",
      whatHappened: "Your claim entered automated validation.",
      whyItHappened: "EPF systems validate base eligibility before manual review.",
      userImpact: "No action is needed unless a mismatch is found.",
      nextSteps: ["Keep profile details up to date."],
    },
  },
  {
    key: "kyc_verification",
    label: "Identity and KYC verification",
    detail: "Aadhaar, PAN, and bank records are validated for claim readiness.",
    owner: "epfo",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "1 business day",
    nextStep: "Employer verification if required",
    explanation: {
      owner: "epfo",
      whatHappened: "KYC and identity checks are underway.",
      whyItHappened: "Identity matching is mandatory before payout approval.",
      userImpact: "Mismatches can pause processing until corrected.",
      nextSteps: ["Review KYC pipeline in Profile if flagged."],
    },
  },
  {
    key: "employer_verification",
    label: "Employer verification",
    detail: "Employer-side contribution/service records are being validated.",
    owner: "employer",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "1-2 business days",
    nextStep: "Assigned for processing",
    explanation: {
      owner: "employer",
      whatHappened: "Employer-linked records are being cross-checked.",
      whyItHappened: "Claim eligibility depends on filed payroll and service records.",
      userImpact: "Delay is possible if employer records are incomplete.",
      nextSteps: ["Contact employer only if this stage is stuck for long."],
    },
  },
  {
    key: "assigned_processing",
    label: "Assigned for processing",
    detail: "A processing officer queue has been assigned.",
    owner: "epfo",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "Within 1 business day",
    nextStep: "Under review",
    explanation: {
      owner: "epfo",
      whatHappened: "Your claim is assigned to a processing queue.",
      whyItHappened: "Automated checks finished and moved to officer workflow.",
      userImpact: "The claim is advancing normally.",
      nextSteps: ["Wait for review decision."],
    },
  },
  {
    key: "under_review",
    label: "Under review",
    detail: "EPFO is reviewing claim details and supporting records.",
    owner: "epfo",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "2-4 business days",
    nextStep: "Processing",
    explanation: {
      owner: "epfo",
      whatHappened: "Your claim is being reviewed by EPFO.",
      whyItHappened: "Records are being validated before approval.",
      userImpact: "No user action is needed at this time.",
      nextSteps: ["Monitor updates if ownership changes."],
    },
  },
  {
    key: "processing",
    label: "Processing",
    detail: "Claim is approved and payout processing has started.",
    owner: "epfo",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "1-2 business days",
    nextStep: "Payment initiated",
    explanation: {
      owner: "epfo",
      whatHappened: "Claim is approved and moving to payment systems.",
      whyItHappened: "Review checks are complete.",
      userImpact: "You should see payout movement soon.",
      nextSteps: ["Verify bank status stays ready."],
    },
  },
  {
    key: "payment_initiated",
    label: "Payment initiated",
    detail: "Payment instruction has been sent to the linked bank.",
    owner: "bank",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "Up to 24 hours",
    nextStep: "Completed",
    explanation: {
      owner: "bank",
      whatHappened: "Payment has been initiated to your bank account.",
      whyItHappened: "EPFO approved and sent payout instructions.",
      userImpact: "Credit should reflect after bank processing.",
      nextSteps: ["Check account credit and report delay if needed."],
    },
  },
  {
    key: "completed",
    label: "Completed",
    detail: "Claim lifecycle is complete.",
    owner: "epfo",
    requiresUserAction: false,
    userAction: "None required",
    expectedDuration: "Finished",
    nextStep: "No further steps",
    explanation: {
      owner: "epfo",
      whatHappened: "Your claim has been completed.",
      whyItHappened: "All processing and payout checks finished.",
      userImpact: "No further action is required.",
      nextSteps: ["Download or keep records for reference."],
    },
  },
];

function makeTimeline(currentStage: Claim["currentStage"], submittedDate: string): ClaimStage[] {
  const currentIndex = claimStageSequence.findIndex((stage) => stage.key === currentStage);
  return claimStageSequence.map((stage, index) => ({
    key: stage.key,
    label: stage.label,
    detail: stage.detail,
    owner: stage.owner,
    requiresUserAction: stage.requiresUserAction,
    userAction: stage.userAction,
    expectedDuration: stage.expectedDuration,
    nextStep: stage.nextStep,
    explainability: stage.explanation,
    timestamp:
      index <= currentIndex
        ? new Date(new Date(submittedDate).getTime() + index * 72_00_000).toISOString()
        : undefined,
    state: index < currentIndex ? "done" : index === currentIndex ? "current" : "upcoming",
  }));
}

function makeActivity(currentStage: Claim["currentStage"], submittedDate: string): ClaimActivityEvent[] {
  return makeTimeline(currentStage, submittedDate).map((stage) => ({
    id: `ACT-${stage.key}`,
    key: stage.key,
    occurredAt: stage.timestamp,
    title: stage.label,
    owner: stage.owner,
    status:
      stage.state === "done" ? "completed" : stage.state === "current" ? "current" : "upcoming",
    detail: stage.detail,
    explainability: stage.explainability,
  }));
}

export const mockClaims: Claim[] = [
  {
    id: "CLM-ACTIVE-001",
    referenceNumber: "NIDHI-2026-00091",
    type: "medical_advance",
    amount: 75000,
    createdAt: "2026-08-10T11:00:00.000Z",
    lastUpdated: "2026-08-24T08:15:00.000Z",
    status: "active",
    statusCategory: "in_progress",
    currentOwner: "epfo",
    actionRequired: false,
    userAction: "None required",
    expectedNextStep: "Processing",
    expectedProcessingTime: "2-4 business days",
    currentStage: "under_review",
    timeline: makeTimeline("under_review", "2026-08-10T11:00:00.000Z"),
    activity: makeActivity("under_review", "2026-08-10T11:00:00.000Z"),
    nextAction: "No action needed now. EPFO owns this stage.",
  },
  {
    id: "CLM-COMPLETE-001",
    referenceNumber: "NIDHI-2025-00143",
    type: "transfer",
    amount: 0,
    createdAt: "2025-12-18T10:30:00.000Z",
    lastUpdated: "2025-12-24T16:00:00.000Z",
    status: "completed",
    statusCategory: "resolved",
    currentOwner: "epfo",
    actionRequired: false,
    userAction: "None required",
    expectedNextStep: "Completed",
    expectedProcessingTime: "Completed",
    currentStage: "completed",
    timeline: makeTimeline("completed", "2025-12-18T10:30:00.000Z"),
    activity: makeActivity("completed", "2025-12-18T10:30:00.000Z"),
    nextAction: "Completed claim. You can download records from Services.",
  },
  {
    id: "CLM-REJECT-001",
    referenceNumber: "NIDHI-2026-00071",
    type: "final_settlement",
    amount: 115000,
    createdAt: "2026-07-28T10:30:00.000Z",
    lastUpdated: "2026-08-02T10:00:00.000Z",
    status: "rejected",
    statusCategory: "action_required",
    currentOwner: "employer",
    actionRequired: true,
    userAction: "Contact previous employer for service history correction.",
    expectedNextStep: "Resubmit after correction",
    expectedProcessingTime: "3-5 business days after correction",
    currentStage: "rejected",
    timeline: makeTimeline("under_review", "2026-07-28T10:30:00.000Z"),
    activity: makeActivity("under_review", "2026-07-28T10:30:00.000Z"),
    nextAction: "Action required: previous employer record must be corrected.",
    rejection: {
      code: "EPS_BIFURCATION_PENDING",
      rawMessage: "EPS not bifurcated by employer. Submit clarification.",
      owner: "employer",
      resolutionSteps: [
        "Review PF Career Map to confirm the affected previous employment record.",
        "Contact previous employer and request EPS bifurcation update.",
        "After update is visible, resubmit claim from Claims page.",
      ],
      ctas: [
        { label: "Review account details", href: "/profile" },
        { label: "Contact employer guidance", href: "/help" },
        { label: "Ask Nidhi for guidance", href: "/claims" },
      ],
      explainability: {
        owner: "employer",
        whatHappened: "Your claim needs additional information before approval.",
        whyItHappened:
          "EPS contribution split from a previous employer record is incomplete.",
        userImpact:
          "The claim cannot proceed until the employer-side service record is corrected.",
        nextSteps: [
          "Contact previous employer for EPS bifurcation completion.",
          "Raise a grievance if correction is delayed.",
          "Resubmit after records are updated.",
        ],
      },
    },
  },
  {
    id: "CLM-DRAFT-001",
    referenceNumber: "NIDHI-DR-2026-0007",
    type: "medical_advance",
    amount: 40000,
    createdAt: "2026-08-20T14:15:00.000Z",
    lastUpdated: "2026-08-20T14:15:00.000Z",
    status: "draft",
    statusCategory: "informational",
    currentOwner: "user",
    actionRequired: true,
    userAction: "Review and submit this draft claim.",
    expectedNextStep: "Submit claim",
    expectedProcessingTime: "Immediately after submission",
    currentStage: "submitted",
    timeline: makeTimeline("submitted", "2026-08-20T14:15:00.000Z"),
    activity: makeActivity("submitted", "2026-08-20T14:15:00.000Z"),
    nextAction: "Review and submit your draft claim.",
  },
];

export const mockProfile: MemberProfile = {
  memberId: "MHBAN0012345000",
  name: "Zaakir Hussain",
  uan: "UAN-XXXX-1234",
  uanStatus: "active",
  dateOfBirth: "1991-04-12",
  mobile: "+91 90000 12345",
  email: "zaakir.hussain@nidhi-portal.test",
  kyc: {
    aadhaarMasked: "XXXX-XXXX-1122",
    panMasked: "ABCDE****F",
    aadhaarStatus: "verified",
    panStatus: "verified",
    pipeline: [
      {
        id: "kyc-submitted",
        label: "Submitted",
        status: "completed",
        owner: "user",
        detail: "Identity records submitted for verification.",
      },
      {
        id: "kyc-validation",
        label: "Identity matching",
        status: "completed",
        owner: "epfo",
        detail: "Aadhaar and PAN records matched.",
      },
      {
        id: "kyc-ready",
        label: "Ready for claims",
        status: "completed",
        owner: "epfo",
        detail: "KYC is ready for claim processing.",
      },
    ],
    mismatches: [],
  },
  employment: [
    {
      employerName: "Nidhi Manufacturing Pvt Ltd",
      memberId: "MHBAN0012345000",
      uanLinked: "UAN-XXXX-1234",
      dojEpf: "2024-07-01",
      status: "current",
      transferStatus: "not_applicable",
      serviceHistoryStatus: "complete",
      integrityFlags: [],
    },
    {
      employerName: "Sample Textiles Limited",
      memberId: "MHBAN0099887000",
      uanLinked: "UAN-XXXX-1234",
      dojEpf: "2022-04-01",
      doeEpf: undefined,
      status: "past",
      transferStatus: "needs_attention",
      serviceHistoryStatus: "needs_review",
      integrityFlags: ["missing_date_of_exit", "untransferred_pf_balance"],
    },
  ],
  bank: {
    accountMasked: "XXXXXX2109",
    ifscMasked: "IDFB0XXXXX",
    status: "pending",
    pipeline: [
      {
        id: "bank-submitted",
        label: "Submitted",
        status: "completed",
        owner: "user",
        detail: "Bank details submitted.",
      },
      {
        id: "bank-validated",
        label: "Bank validation",
        status: "completed",
        owner: "bank",
        detail: "Account format and IFSC are valid.",
      },
      {
        id: "bank-match",
        label: "Identity matching",
        status: "in_progress",
        owner: "epfo",
        detail: "Name matching with EPFO records is in progress.",
      },
      {
        id: "bank-ready",
        label: "Ready for claims",
        status: "blocked",
        owner: "epfo",
        detail: "Blocked until identity matching completes.",
      },
    ],
    mismatches: [
      {
        id: "bank-name-mismatch",
        field: "Account holder name",
        epfoValue: "Zaakir Hussain",
        sourceValue: "Zaakir H Hussain",
        owner: "user",
        cta: { label: "Start correction", href: "/profile" },
        explainability: {
          owner: "user",
          whatHappened: "Your bank account name has a minor mismatch.",
          whyItHappened:
            "The bank record includes a middle initial that does not fully match EPFO profile.",
          userImpact: "Claim payout may not start until name match is accepted or corrected.",
          nextSteps: [
            "Update profile/bank record for exact name match.",
            "Re-run verification in claim flow.",
          ],
        },
      },
    ],
    readyForClaims: false,
  },
  nominees: [
    {
      id: "NOM-001",
      name: "Sana Member",
      relationship: "Spouse",
      sharePercent: 100,
      dob: "1992-08-09",
    },
  ],
  careerSummary: {
    totalEligibleServiceMonths: 49,
    totalPfAccountsDetected: 2,
    reconciledAccounts: 1,
    accountsRequiringAttention: 1,
  },
};

export const mockServices: Service[] = [
  {
    id: "svc-transfer",
    title: "Transfer EPF",
    description: "Move PF balance from previous member ID to current account.",
    estimatedSteps: 4,
    isAvailable: false,
  },
  {
    id: "svc-medical-claim",
    title: "Start medical advance claim",
    description: "Raise a medical advance claim with guided steps.",
    estimatedSteps: 5,
    isAvailable: true,
  },
  {
    id: "svc-track-claim",
    title: "Track a claim",
    description: "See claim timeline, current stage and expected next action.",
    estimatedSteps: 2,
    isAvailable: true,
  },
  {
    id: "svc-profile",
    title: "Update profile details",
    description: "Review and edit basic profile and nominee information.",
    estimatedSteps: 3,
    isAvailable: true,
  },
];

export const mockServiceStatus: ServiceStatus[] = [
  {
    id: "svc-status-member",
    name: "Member account",
    status: "operational",
    owner: "epfo",
    lastUpdated: "2026-08-24T08:20:00.000Z",
    detail: "Member profile and balance retrieval is operational.",
    draftsSafe: true,
  },
  {
    id: "svc-status-claims",
    name: "Claims",
    status: "degraded",
    owner: "epfo",
    lastUpdated: "2026-08-24T08:18:00.000Z",
    detail: "Some claims are taking longer during employer verification.",
    estimatedRestoration: "Expected normalization within 6 hours",
    draftsSafe: true,
  },
  {
    id: "svc-status-passbook",
    name: "Passbook",
    status: "operational",
    owner: "epfo",
    lastUpdated: "2026-08-24T08:22:00.000Z",
    detail: "Passbook updates are current.",
    draftsSafe: true,
  },
  {
    id: "svc-status-kyc",
    name: "KYC",
    status: "degraded",
    owner: "epfo",
    lastUpdated: "2026-08-24T08:21:00.000Z",
    detail: "Identity matching is slower than usual for some records.",
    estimatedRestoration: "Monitoring; next update in 2 hours",
    draftsSafe: true,
  },
  {
    id: "svc-status-transfer",
    name: "Transfers",
    status: "degraded",
    owner: "epfo",
    lastUpdated: "2026-08-24T08:19:00.000Z",
    detail: "Previous account reconciliation queue is delayed.",
    estimatedRestoration: "Expected normalization by end of day",
    draftsSafe: true,
  },
  {
    id: "svc-status-profile",
    name: "Profile services",
    status: "operational",
    owner: "epfo",
    lastUpdated: "2026-08-24T08:23:00.000Z",
    detail: "Profile edits and nominee updates are available.",
    draftsSafe: true,
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "TCK-001",
    referenceNumber: "SUP-2026-0102",
    subject: "June passbook contribution looks lower than usual",
    category: "passbook",
    description:
      "The June 2026 contribution is lower than nearby months. Please confirm if this is expected in the account record.",
    status: "in_progress",
    statusCategory: "in_progress",
    currentOwner: "epfo",
    createdAt: "2026-08-18T09:00:00.000Z",
    lastUpdate: "2026-08-19T12:00:00.000Z",
    nextExpectedAction: "EPFO review response expected within 1 business day.",
    timeline: [
      {
        id: "TCK-001-E1",
        occurredAt: "2026-08-18T09:00:00.000Z",
        owner: "user",
        status: "open",
        detail: "You reported a lower contribution in June 2026.",
      },
      {
        id: "TCK-001-E2",
        occurredAt: "2026-08-18T10:10:00.000Z",
        owner: "user",
        status: "open",
        detail: "Passbook screenshot evidence submitted.",
        documents: ["June-2026-passbook-snapshot.png"],
      },
      {
        id: "TCK-001-E3",
        occurredAt: "2026-08-19T12:00:00.000Z",
        owner: "epfo",
        status: "in_progress",
        detail: "Case assigned to passbook reconciliation desk.",
      },
    ],
  },
  {
    id: "TCK-002",
    referenceNumber: "SUP-2026-0091",
    subject: "Transfer status still pending after job change",
    category: "account",
    description:
      "Previous PF transfer still shows pending. Need help to reconcile member accounts.",
    status: "resolved",
    statusCategory: "resolved",
    currentOwner: "epfo",
    createdAt: "2026-08-02T10:30:00.000Z",
    lastUpdate: "2026-08-05T13:00:00.000Z",
    nextExpectedAction: "Confirm whether issue is actually resolved.",
    closureReason: "Transfer queue update applied and reflected in account summary.",
    timeline: [
      {
        id: "TCK-002-E1",
        occurredAt: "2026-08-02T10:30:00.000Z",
        owner: "user",
        status: "open",
        detail: "Case reported for pending transfer.",
      },
      {
        id: "TCK-002-E2",
        occurredAt: "2026-08-03T09:45:00.000Z",
        owner: "epfo",
        status: "in_progress",
        detail: "Case moved to transfer reconciliation queue.",
      },
      {
        id: "TCK-002-E3",
        occurredAt: "2026-08-05T13:00:00.000Z",
        owner: "epfo",
        status: "resolved",
        detail: "Transfer status updated after account reconciliation.",
      },
    ],
  },
];
